/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.senai.sp.jandira.gui;

import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 22282201
 */
public class AgendaDeConsultas extends javax.swing.JFrame {

    /**
     * Creates new form AgendaDeConsultas
     */
    public AgendaDeConsultas() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/senai/sp/jandira/images/299092_calendar_icon.png")));
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelEspecialidades = new javax.swing.JPanel();
        scrollTable = new javax.swing.JScrollPane();
        tableEspecialidadescadastradas = new javax.swing.JTable();
        buttonDeletar = new javax.swing.JButton();
        buttonAdicionar = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();
        buttonSair = new javax.swing.JButton();
        buttonAgenda = new javax.swing.JButton();
        buttonPaciente = new javax.swing.JButton();
        buttonMedicos = new javax.swing.JButton();
        buttonEspecialidades = new javax.swing.JButton();
        buttonPlanoSaude = new javax.swing.JButton();
        panelHeader = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelAgenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Agendamentos");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(null);

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setLayout(null);

        panelEspecialidades.setBackground(new java.awt.Color(255, 255, 255));
        panelEspecialidades.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Especialidades médicas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 102, 204))); // NOI18N
        panelEspecialidades.setForeground(new java.awt.Color(0, 102, 255));
        panelEspecialidades.setOpaque(false);
        panelEspecialidades.setLayout(null);

        tableEspecialidadescadastradas.setBackground(new java.awt.Color(255, 255, 255));
        tableEspecialidadescadastradas.setForeground(new java.awt.Color(0, 0, 0));
        tableEspecialidadescadastradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTable.setViewportView(tableEspecialidadescadastradas);

        panelEspecialidades.add(scrollTable);
        scrollTable.setBounds(20, 30, 940, 280);

        buttonDeletar.setBackground(new java.awt.Color(255, 255, 255));
        buttonDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/images/1312512_circle_delete_style_trash_remove_icon.png"))); // NOI18N
        buttonDeletar.setToolTipText("Deletar Especialidades");
        buttonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeletarActionPerformed(evt);
            }
        });
        panelEspecialidades.add(buttonDeletar);
        buttonDeletar.setBounds(790, 320, 40, 40);

        buttonAdicionar.setBackground(new java.awt.Color(255, 255, 255));
        buttonAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/images/6586117_add_create_new_plus_icon.png"))); // NOI18N
        buttonAdicionar.setToolTipText("Adicionar Especialidades");
        buttonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarActionPerformed(evt);
            }
        });
        panelEspecialidades.add(buttonAdicionar);
        buttonAdicionar.setBounds(910, 320, 40, 40);

        buttonEditar.setBackground(new java.awt.Color(255, 255, 255));
        buttonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/images/1311613_circle_edit_line_pen_design_icon.png"))); // NOI18N
        buttonEditar.setToolTipText("Editar Especialidades");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });
        panelEspecialidades.add(buttonEditar);
        buttonEditar.setBounds(850, 320, 40, 40);

        panelMain.add(panelEspecialidades);
        panelEspecialidades.setBounds(10, 70, 980, 370);

        buttonSair.setBackground(new java.awt.Color(204, 255, 255));
        buttonSair.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonSair.setForeground(new java.awt.Color(51, 51, 51));
        buttonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/images/9161303_log_out_input_access_security_icon.png"))); // NOI18N
        buttonSair.setText("Sair");
        buttonSair.setToolTipText("Sair");
        panelMain.add(buttonSair);
        buttonSair.setBounds(870, 30, 100, 30);

        buttonAgenda.setBackground(new java.awt.Color(204, 255, 255));
        buttonAgenda.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonAgenda.setForeground(new java.awt.Color(51, 51, 51));
        buttonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/images/299092_calendar_icon (1).png"))); // NOI18N
        buttonAgenda.setText("Agenda");
        buttonAgenda.setToolTipText("Agendamentos");
        panelMain.add(buttonAgenda);
        buttonAgenda.setBounds(20, 30, 110, 30);

        buttonPaciente.setBackground(new java.awt.Color(204, 255, 255));
        buttonPaciente.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonPaciente.setForeground(new java.awt.Color(51, 51, 51));
        buttonPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/images/6141458_cold_covid19_sick_sickness_a fever_icon.png"))); // NOI18N
        buttonPaciente.setText("Paciente");
        buttonPaciente.setToolTipText("Pacientes");
        panelMain.add(buttonPaciente);
        buttonPaciente.setBounds(140, 30, 110, 30);

        buttonMedicos.setBackground(new java.awt.Color(204, 255, 255));
        buttonMedicos.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonMedicos.setForeground(new java.awt.Color(51, 51, 51));
        buttonMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/images/6014551_asian_coronavirus_doctor_male_icon.png"))); // NOI18N
        buttonMedicos.setText("Médicos");
        buttonMedicos.setToolTipText("Médicos");
        panelMain.add(buttonMedicos);
        buttonMedicos.setBounds(260, 30, 110, 30);

        buttonEspecialidades.setBackground(new java.awt.Color(204, 255, 255));
        buttonEspecialidades.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonEspecialidades.setForeground(new java.awt.Color(51, 51, 51));
        buttonEspecialidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/images/especialidades.png"))); // NOI18N
        buttonEspecialidades.setText("Especialidades");
        buttonEspecialidades.setToolTipText("Especialidades");
        panelMain.add(buttonEspecialidades);
        buttonEspecialidades.setBounds(380, 30, 160, 30);

        buttonPlanoSaude.setBackground(new java.awt.Color(204, 255, 255));
        buttonPlanoSaude.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonPlanoSaude.setForeground(new java.awt.Color(51, 51, 51));
        buttonPlanoSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/images/2142681_badge_data_id_identification_profile_icon.png"))); // NOI18N
        buttonPlanoSaude.setText("Plano de Saúde");
        buttonPlanoSaude.setToolTipText("Planos de saúde");
        buttonPlanoSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlanoSaudeActionPerformed(evt);
            }
        });
        panelMain.add(buttonPlanoSaude);
        buttonPlanoSaude.setBounds(550, 30, 170, 30);

        getContentPane().add(panelMain);
        panelMain.setBounds(0, 90, 1000, 490);

        panelHeader.setBackground(new java.awt.Color(102, 204, 255));
        panelHeader.setLayout(null);

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 0, 255));
        labelTitulo.setText("Agenda de Consultas");
        panelHeader.add(labelTitulo);
        labelTitulo.setBounds(90, 20, 250, 50);

        labelAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/images/299092_calendar_icon.png"))); // NOI18N
        panelHeader.add(labelAgenda);
        labelAgenda.setBounds(20, 10, 60, 70);

        getContentPane().add(panelHeader);
        panelHeader.setBounds(0, 0, 1000, 90);

        setSize(new java.awt.Dimension(1014, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDeletarActionPerformed

    private void buttonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAdicionarActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonPlanoSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlanoSaudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPlanoSaudeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionar;
    private javax.swing.JButton buttonAgenda;
    private javax.swing.JButton buttonDeletar;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonEspecialidades;
    private javax.swing.JButton buttonMedicos;
    private javax.swing.JButton buttonPaciente;
    private javax.swing.JButton buttonPlanoSaude;
    private javax.swing.JButton buttonSair;
    private javax.swing.JLabel labelAgenda;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelEspecialidades;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMain;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTable tableEspecialidadescadastradas;
    // End of variables declaration//GEN-END:variables

    private void preencherTabela() {

        String[][] dados = {
            {"100", "Jandira", "SP"},
            {"200", "Itapevi", "SP"},
            {"300", "Cotia", "SP"},
            {"400", "Barueri", "SP"},
            {"500", "Curitiba", "SP"},
            {"600", "Fortaleza", "SP"},};

        String[] titulos = {"CÓDIGO", "CIDADE", "ESTADO"};

        DefaultTableModel modelo = new DefaultTableModel(dados, titulos);
        tableEspecialidadescadastradas.setModel(modelo);
    }

}
