/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.senai.sp.jandira.gui;

import br.senai.sp.jandira.dao.EspecialidadeDAO;
import br.senai.sp.jandira.model.Especialidade;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author 22282201
 */
public class EspecialidadeDialog extends javax.swing.JDialog {

    /**
     * Creates new form EspecialidadeDialog
     */
    public EspecialidadeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/senai/sp/jandira/images/adicionar.png")));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        panelAdicionarEspecialidade = new javax.swing.JPanel();
        labelCodigo = new javax.swing.JLabel();
        textFieldCodigo = new javax.swing.JTextField();
        textFieldNomeEspecialidade = new javax.swing.JTextField();
        labelNomeEspecialidade = new javax.swing.JLabel();
        textFieldDescricaoEspecialidade = new javax.swing.JTextField();
        labelDescricaoEspecialidade = new javax.swing.JLabel();
        buttonCancel = new javax.swing.JButton();
        buttonSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Especialidades");
        setPreferredSize(new java.awt.Dimension(650, 440));
        setResizable(false);
        setSize(new java.awt.Dimension(680, 440));
        getContentPane().setLayout(null);

        panelHeader.setBackground(new java.awt.Color(102, 204, 255));
        panelHeader.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/images/adicionar.png"))); // NOI18N
        jLabel1.setText(" Adicionar - ESPECIALIDADES");
        panelHeader.add(jLabel1);
        jLabel1.setBounds(20, 10, 610, 40);

        getContentPane().add(panelHeader);
        panelHeader.setBounds(0, 0, 650, 60);

        panelMain.setBackground(new java.awt.Color(248, 248, 248));
        panelMain.setLayout(null);

        panelAdicionarEspecialidade.setBackground(new java.awt.Color(232, 232, 232));
        panelAdicionarEspecialidade.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Especialidades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 102, 204))); // NOI18N
        panelAdicionarEspecialidade.setLayout(null);

        labelCodigo.setBackground(new java.awt.Color(0, 0, 0));
        labelCodigo.setForeground(new java.awt.Color(0, 0, 0));
        labelCodigo.setText("Código:");
        panelAdicionarEspecialidade.add(labelCodigo);
        labelCodigo.setBounds(40, 80, 80, 16);

        textFieldCodigo.setEditable(false);
        textFieldCodigo.setBackground(new java.awt.Color(255, 255, 255));
        textFieldCodigo.setForeground(new java.awt.Color(0, 0, 0));
        panelAdicionarEspecialidade.add(textFieldCodigo);
        textFieldCodigo.setBounds(40, 100, 80, 22);

        textFieldNomeEspecialidade.setBackground(new java.awt.Color(255, 255, 255));
        textFieldNomeEspecialidade.setForeground(new java.awt.Color(0, 0, 0));
        panelAdicionarEspecialidade.add(textFieldNomeEspecialidade);
        textFieldNomeEspecialidade.setBounds(40, 160, 300, 22);

        labelNomeEspecialidade.setForeground(new java.awt.Color(0, 0, 0));
        labelNomeEspecialidade.setText("Nome da Especialidade:");
        panelAdicionarEspecialidade.add(labelNomeEspecialidade);
        labelNomeEspecialidade.setBounds(40, 140, 300, 16);

        textFieldDescricaoEspecialidade.setBackground(new java.awt.Color(255, 255, 255));
        textFieldDescricaoEspecialidade.setForeground(new java.awt.Color(0, 0, 0));
        panelAdicionarEspecialidade.add(textFieldDescricaoEspecialidade);
        textFieldDescricaoEspecialidade.setBounds(40, 220, 530, 22);

        labelDescricaoEspecialidade.setForeground(new java.awt.Color(0, 0, 0));
        labelDescricaoEspecialidade.setText("Descrição da Especialidade:");
        panelAdicionarEspecialidade.add(labelDescricaoEspecialidade);
        labelDescricaoEspecialidade.setBounds(40, 200, 530, 16);

        buttonCancel.setBackground(new java.awt.Color(255, 255, 255));
        buttonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/images/cancelar.png"))); // NOI18N
        buttonCancel.setToolTipText("Cancelar");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        panelAdicionarEspecialidade.add(buttonCancel);
        buttonCancel.setBounds(500, 310, 40, 40);

        buttonSalvar.setBackground(new java.awt.Color(255, 255, 255));
        buttonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/images/salvar.png"))); // NOI18N
        buttonSalvar.setToolTipText("Salvar Especialidade");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });
        panelAdicionarEspecialidade.add(buttonSalvar);
        buttonSalvar.setBounds(560, 310, 40, 40);

        panelMain.add(panelAdicionarEspecialidade);
        panelAdicionarEspecialidade.setBounds(10, 10, 630, 360);

        getContentPane().add(panelMain);
        panelMain.setBounds(0, 60, 650, 410);

        setSize(new java.awt.Dimension(665, 476));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed

        //Criar objeto especialidade
        Especialidade especialidade = new Especialidade();
        especialidade.setNome(textFieldNomeEspecialidade.getText());
        especialidade.setDescricao(textFieldDescricaoEspecialidade.getText());

        //Gravar o objeto, através do DAO
        EspecialidadeDAO.gravar(especialidade);

        JOptionPane.showMessageDialog(this, "Especialidade Gravada com Sucesso!", "Especialidades - Adicionar", JOptionPane.INFORMATION_MESSAGE, null);
        dispose();
        
    }//GEN-LAST:event_buttonSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EspecialidadeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EspecialidadeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EspecialidadeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EspecialidadeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EspecialidadeDialog dialog = new EspecialidadeDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelDescricaoEspecialidade;
    private javax.swing.JLabel labelNomeEspecialidade;
    private javax.swing.JPanel panelAdicionarEspecialidade;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMain;
    private javax.swing.JTextField textFieldCodigo;
    private javax.swing.JTextField textFieldDescricaoEspecialidade;
    private javax.swing.JTextField textFieldNomeEspecialidade;
    // End of variables declaration//GEN-END:variables
}
